# -*- coding: utf-8 -*-
"""
1_pre_cache_krea2.py — Pre-cache of latents + embeddings for Krea 2 (RAW)

Reads configuration from pre_cache_settings.json if present.
"""
import os
import gc
import math
import json
import hashlib
import torch
import torchvision.transforms.functional as F_vision
from PIL import Image
from diffusers import DiffusionPipeline
import sys

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass

# Project root (this script lives in scripts/python/). All paths are
# anchored here instead of the working directory, so it works when
# invoked from anywhere.
PROJECT_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


def from_root(path):
    """Resolves a relative path against project root (absolute paths left intact)."""
    return path if os.path.isabs(path) else os.path.normpath(os.path.join(PROJECT_ROOT, path))


# Container folder for everything generated by pre-cache (a single one at the root).
CACHE_ROOT = os.path.join(PROJECT_ROOT, "cached_data_local")

# ── DEFAULTS ────────────────────────────────────────────────────────────────
DEFAULTS = {
    "model_id": "Krea-2-NF4",
    "dataset_path": "./dataset",
    "cache_dir": f"{CACHE_ROOT}/default",
    "target_area": 512 * 512,
    "max_side": 1280,
    "multiple": 16,
    "max_seq_len": 128,
    "project_name": "",
    "trigger_word": "",
    "resolutions": [],

    # ── D1: manifest and cache invalidation ─────────────────────────────────
    "cache_key": "mtime",        # "mtime" | "sha1"
    "prune_orphans": "warn",     # "warn" | "delete" | "off"
    "force_recache": False,
    # ── D2: horizontal flip augmentation ────────────────────────────────────
    "flip_x": False,
    # ── C5: preview prompts ──────────────────────────────────────────────────
    "sample_prompts": [],
}

# Incremented when latent normalization or packing changes, to
# automatically invalidate all existing caches.
LATENT_VERSION = 1

# ── LOAD CONFIG ─────────────────────────────────────────────────────────────
CONFIG_PATH = os.environ.get("PRECACHE_SETTINGS_PATH",
                             os.path.join(PROJECT_ROOT, "pre_cache_settings.json"))

if os.path.exists(CONFIG_PATH):
    with open(CONFIG_PATH, "r", encoding="utf-8") as f:
        cfg = json.load(f)
    print(f"✓ Configuration loaded from {CONFIG_PATH}")
else:
    cfg = {}
    print(f"⚠ {CONFIG_PATH} not found, using defaults.")

MODEL_ID     = cfg.get("model_id",     DEFAULTS["model_id"])
# The local model lives at the project root. It is anchored only if the folder
# exists there, so as not to break the case of a Hugging Face repo-id; without this,
# running from another directory would trigger a full model download.
if not os.path.isabs(MODEL_ID) and os.path.isdir(from_root(MODEL_ID)):
    MODEL_ID = from_root(MODEL_ID)
DATASET_PATH = from_root(cfg.get("dataset_path", DEFAULTS["dataset_path"]))
TARGET_AREA  = cfg.get("target_area",  DEFAULTS["target_area"])
MAX_SIDE     = cfg.get("max_side",     DEFAULTS["max_side"])
MULTIPLE     = cfg.get("multiple",     DEFAULTS["multiple"])
MAX_SEQ_LEN  = cfg.get("max_seq_len",  DEFAULTS["max_seq_len"])
TRIGGER_WORD = cfg.get("trigger_word", "")
PROJECT_NAME = cfg.get("project_name", "").strip()

# Progressive resolution: if 'resolutions' contains a list of areas, the dataset
# is pre-cached to each one in a {label}/ subdirectory. If empty, the single
# resolution from 'target_area' is used (classic, backward-compatible behavior).
RESOLUTIONS = cfg.get("resolutions", DEFAULTS["resolutions"]) or []

CACHE_KEY     = str(cfg.get("cache_key", DEFAULTS["cache_key"])).strip().lower()
PRUNE_ORPHANS = str(cfg.get("prune_orphans", DEFAULTS["prune_orphans"])).strip().lower()
FORCE_RECACHE = bool(cfg.get("force_recache", DEFAULTS["force_recache"]))
FLIP_X        = bool(cfg.get("flip_x", DEFAULTS["flip_x"]))
SAMPLE_PROMPTS = list(cfg.get("sample_prompts", DEFAULTS["sample_prompts"]) or [])

if CACHE_KEY not in ("mtime", "sha1"):
    print(f"⚠ Invalid cache_key '{CACHE_KEY}'. Using 'mtime'.")
    CACHE_KEY = "mtime"
if PRUNE_ORPHANS not in ("warn", "delete", "off"):
    print(f"⚠ Invalid prune_orphans '{PRUNE_ORPHANS}'. Using 'warn'.")
    PRUNE_ORPHANS = "warn"


def res_label(area):
    """Short label for the subdirectory based on area (e.g. 589824 -> '768')."""
    return str(int(round(math.sqrt(area))))

# Automatic formatting of cache folder based on project name.
# Everything generated is grouped under CACHE_ROOT to avoid cluttering the root directory.
# Without project_name, an explicit cache_dir is respected (used by run_progressive.py
# to point to each phase's resolution subdirectory).
if PROJECT_NAME:
    CACHE_DIR = os.path.join(CACHE_ROOT, PROJECT_NAME)
else:
    CACHE_DIR = from_root(cfg.get("cache_dir", DEFAULTS["cache_dir"]))

# Validate that Multiple is exclusively 16, 32, or 64 (Default: 16).
# 8 is invalid: trainer's pack_latents() divides latent dimensions (px/8)
# by 2, so pixel dimensions must be multiples of 16 or packing quietly corrupts.
if MULTIPLE not in (16, 32, 64):
    print(f"⚠ Invalid Multiple {MULTIPLE}. Defaulting to 16.")
    MULTIPLE = 16

print(f"  Model ID                  : {MODEL_ID}")
print(f"  Project Name              : {PROJECT_NAME if PROJECT_NAME else '(Default)'}")
print(f"  Trigger Word              : {TRIGGER_WORD}")
print(f"  Dataset Path              : {DATASET_PATH}")
print(f"  Cache Dir                 : {CACHE_DIR}")
if RESOLUTIONS:
    print(f"  Resolutions               : {[res_label(a)+'²' for a in RESOLUTIONS]}")
else:
    print(f"  Target Area               : {TARGET_AREA} px²")
print(f"  Max Side                  : {MAX_SIDE}")
print(f"  Multiple                  : {MULTIPLE}")
print(f"  Max Seq Len               : {MAX_SEQ_LEN}")
print(f"  Cache key                 : {CACHE_KEY} (prune_orphans={PRUNE_ORPHANS}"
      f"{', force_recache' if FORCE_RECACHE else ''})")
print(f"  Flip augmentation         : {'ON (doubles dataset)' if FLIP_X else 'OFF'}")
if SAMPLE_PROMPTS:
    print(f"  Sample prompts            : {len(SAMPLE_PROMPTS)}")

os.makedirs(DATASET_PATH, exist_ok=True)
os.makedirs(CACHE_DIR, exist_ok=True)


def free_vram(*tensors):
    for t in tensors:
        del t
    gc.collect()
    torch.cuda.empty_cache()


def bucket_size(w: int, h: int, area=None):
    """(width, height) multiples of MULTIPLE, area ≈ `area`, preserving aspect ratio."""
    if area is None:
        area = TARGET_AREA
    ar = w / h
    bh = math.sqrt(area / ar)
    bw = ar * bh
    bw = max(MULTIPLE, round(bw / MULTIPLE) * MULTIPLE)
    bh = max(MULTIPLE, round(bh / MULTIPLE) * MULTIPLE)
    if max(bw, bh) > MAX_SIDE:
        s = MAX_SIDE / max(bw, bh)
        bw = max(MULTIPLE, int(bw * s) // MULTIPLE * MULTIPLE)
        bh = max(MULTIPLE, int(bh * s) // MULTIPLE * MULTIPLE)
    return bw, bh


# ── D1: CACHE MANIFEST ───────────────────────────────────────────────────────

def manifest_config():
    """Settings that, if modified, invalidate all existing cached latents."""
    return {
        "multiple": MULTIPLE,
        "max_side": MAX_SIDE,
        "max_seq_len": MAX_SEQ_LEN,
        "trigger_word": TRIGGER_WORD,
        "flip_x": FLIP_X,
        "latent_version": LATENT_VERSION,
    }


def load_manifest(out_dir):
    path = os.path.join(out_dir, "cache_manifest.json")
    if not os.path.exists(path):
        return {"version": 1, "config": {}, "entries": {}}
    try:
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
        if data.get("config") != manifest_config():
            print(f"   [i] Cache config changed for {os.path.basename(out_dir)}; "
                  f"re-encoding all.")
            return {"version": 1, "config": {}, "entries": {}}
        return data
    except Exception:
        return {"version": 1, "config": {}, "entries": {}}


def save_manifest(out_dir, entries):
    data = {"version": 1, "config": manifest_config(), "entries": entries}
    path = os.path.join(out_dir, "cache_manifest.json")
    tmp = path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    os.replace(tmp, path)


def file_fingerprint(path):
    """Source image fingerprint: mtime+size (fast) or sha1 (robust against duplicate copies)."""
    stat = os.stat(path)
    if CACHE_KEY == "sha1":
        digest = hashlib.sha1()
        with open(path, "rb") as f:
            for chunk in iter(lambda: f.read(1 << 20), b""):
                digest.update(chunk)
        return {"sha1": digest.hexdigest(), "src_size": stat.st_size}
    return {"src_mtime": int(stat.st_mtime), "src_size": stat.st_size}


def caption_fingerprint(text):
    return hashlib.sha1(text.encode("utf-8")).hexdigest()


def prune_orphans(out_dir, valid_names):
    """Latents from deleted or renamed images.

    Without this, they remained in cache permanently and the trainer continued to
    train on them silently; with the epoch sampler, they would also get a guaranteed
    slot every epoch.
    """
    present = {f[:-len("_latent.pt")] for f in os.listdir(out_dir)
               if f.endswith("_latent.pt") and not f.startswith(".")}
    orphans = sorted(present - set(valid_names))
    if not orphans:
        return
    label = os.path.basename(out_dir)
    if PRUNE_ORPHANS == "delete":
        for name in orphans:
            for suffix in ("_latent.pt", "_embed.pt", "_mask.pt"):
                try:
                    os.remove(os.path.join(out_dir, f"{name}{suffix}"))
                except OSError:
                    pass
        print(f"   [OK] Pruned {len(orphans)} orphan entries from {label}.")
    elif PRUNE_ORPHANS == "warn":
        print(f"\n[!] {len(orphans)} orphan cache entries in {label} "
              f"(source image deleted or renamed):")
        for name in orphans[:10]:
            print(f"      {name}")
        if len(orphans) > 10:
            print(f"      ... and {len(orphans) - 10} more")
        print("[!] They will still be trained on. Set prune_orphans='delete' to remove them.")


def ensure_model_downloaded(local_path, repo_id):
    if os.path.exists(local_path) and os.path.isdir(local_path):
        has_content = any(
            os.path.exists(os.path.join(local_path, f))
            for f in ["index.json", "model_index.json", "config.json"]
        ) or len(os.listdir(local_path)) > 0
        if has_content:
            print(f"✓ Local model found at: {local_path}")
            return local_path

    print(f"⚠ Local model not found at: {local_path}")
    print(f"  Downloading from Hugging Face: {repo_id}")
    print(f"  This may take several minutes...")

    try:
        from huggingface_hub import snapshot_download
    except ImportError:
        raise ImportError(
            "huggingface_hub is required. Install with:\n"
            "  pip install huggingface_hub"
        )

    hf_token = cfg.get("hf_token") or os.environ.get("HF_TOKEN")
    dl_kwargs = {
        "repo_id": repo_id,
        "local_dir": local_path,
    }
    if hf_token:
        dl_kwargs["token"] = hf_token

    downloaded_path = snapshot_download(**dl_kwargs)
    print(f"✓ Model downloaded to: {downloaded_path}")
    return downloaded_path


def preprocess_krea2():
    if not os.path.exists(DATASET_PATH):
        print(f"[!] Dataset folder does not exist: {DATASET_PATH}")
        return

    # Auto-cleanup of hidden macOS ghost files (._* and .DS_Store)
    for f in os.listdir(DATASET_PATH):
        if f.startswith("._") or f == ".DS_Store":
            try:
                os.remove(os.path.join(DATASET_PATH, f))
            except Exception:
                pass

    image_files = sorted(f for f in os.listdir(DATASET_PATH)
                         if not f.startswith(".") and f.lower().endswith((".png", ".jpg", ".jpeg", ".webp")))
    if not image_files:
        print(f"[!] No images found in '{DATASET_PATH}'. Please add images and optional .txt files.")
        return

    ensure_model_downloaded(
        local_path=MODEL_ID,
        repo_id="AcademiaSD/Krea-2-NF4-for-LoRA-Training"
    )

    print("Loading VAE (Qwen-Image) and Text Encoder (Qwen3-VL-4B)...")
    pipe = DiffusionPipeline.from_pretrained(
        MODEL_ID,
        transformer=None,
        torch_dtype=torch.bfloat16,
    ).to("cuda")

    if not hasattr(pipe.vae.config, "latents_mean") or not hasattr(pipe.vae.config, "latents_std"):
        raise RuntimeError("This VAE lacks latents_mean/latents_std configuration")

    z_dim = pipe.vae.config.z_dim
    latents_mean = torch.tensor(pipe.vae.config.latents_mean, device="cuda", dtype=torch.float32).view(1, z_dim, 1, 1, 1)
    latents_std  = torch.tensor(pipe.vae.config.latents_std,  device="cuda", dtype=torch.float32).view(1, z_dim, 1, 1, 1)
    print(f"VAE z_dim={z_dim} | Channel normalization OK")

    # Resolution targets: each is a self-contained cache. In progressive
    # mode they go to {label}/ subdirectories; in classic mode, directly to CACHE_DIR.
    if RESOLUTIONS:
        targets = [(os.path.join(CACHE_DIR, res_label(a)), a) for a in RESOLUTIONS]
    else:
        targets = [(CACHE_DIR, TARGET_AREA)]
    for out_dir, _ in targets:
        os.makedirs(out_dir, exist_ok=True)

    def vae_latent(img_pil, area):
        """Resizes/crops to the `area` bucket and returns normalized latent."""
        bw, bh = bucket_size(img_pil.width, img_pil.height, area)
        ratio = max(bw / img_pil.width, bh / img_pil.height)
        im = img_pil.resize((math.ceil(img_pil.width * ratio), math.ceil(img_pil.height * ratio)), Image.LANCZOS)
        left = (im.width - bw) // 2
        top  = (im.height - bh) // 2
        im   = im.crop((left, top, left + bw, top + bh))

        img_tensor = F_vision.pil_to_tensor(im).unsqueeze(0).unsqueeze(2)  # [1,3,1,H,W]
        img_tensor = (img_tensor.float() / 127.5) - 1.0
        img_tensor = img_tensor.to("cuda", dtype=torch.bfloat16)

        z = pipe.vae.encode(img_tensor).latent_dist.sample().float()
        latent = (z - latents_mean) / latents_std
        latent = latent[:, :, 0].to(torch.bfloat16).cpu()
        free_vram(img_tensor, z)
        return bw, bh, latent

    manifests = {out_dir: ({} if FORCE_RECACHE else load_manifest(out_dir))
                 for out_dir, _ in targets}
    reused = encoded = 0

    with torch.inference_mode():
        # The negative embedding is resolution-independent: it is saved in each cache.
        neg_embed, neg_mask = pipe.encode_prompt(prompt="", max_sequence_length=MAX_SEQ_LEN)
        for out_dir, _ in targets:
            torch.save(neg_embed.cpu(), os.path.join(out_dir, "_neg_embed.pt"))
            torch.save(neg_mask.cpu(),  os.path.join(out_dir, "_neg_mask.pt"))
        del neg_embed, neg_mask

        # ── C5: PREVIEW PROMPTS ──────────────────────────────────────────────
        # The trainer loads the pipeline with text_encoder=None and cannot
        # encode arbitrary text, so they are pre-encoded here just like the
        # negative embedding. Zero VRAM cost during training.
        for out_dir, _ in targets:
            for old in os.listdir(out_dir):
                if old.startswith("_sample") and old.endswith((".pt", ".json")):
                    os.remove(os.path.join(out_dir, old))
        for i, item in enumerate(SAMPLE_PROMPTS):
            spec = {"prompt": item} if isinstance(item, str) else dict(item)
            text = str(spec.get("prompt", "")).strip()
            if not text:
                continue
            if TRIGGER_WORD and TRIGGER_WORD.lower() not in text.lower():
                text = f"{TRIGGER_WORD}, {text}".strip(", ")
            s_emb, s_msk = pipe.encode_prompt(prompt=text, max_sequence_length=MAX_SEQ_LEN)
            spec["prompt"] = text
            for out_dir, _ in targets:
                torch.save(s_emb.cpu(), os.path.join(out_dir, f"_sample{i}_embed.pt"))
                torch.save(s_msk.cpu(), os.path.join(out_dir, f"_sample{i}_mask.pt"))
                with open(os.path.join(out_dir, f"_sample{i}_meta.json"), "w", encoding="utf-8") as f:
                    json.dump(spec, f, indent=2, ensure_ascii=False)
            del s_emb, s_msk
            print(f"   [OK] Sample prompt {i} cached: {text[:60]}")

        for idx, file_name in enumerate(image_files, 1):
            stem       = os.path.splitext(file_name)[0]
            text_path  = os.path.join(DATASET_PATH, f"{stem}.txt")
            img_path   = os.path.join(DATASET_PATH, file_name)

            prompt = ""
            if os.path.exists(text_path):
                with open(text_path, "r", encoding="utf-8") as f:
                    prompt = f.read().strip()
            if TRIGGER_WORD and TRIGGER_WORD.lower() not in prompt.lower():
                prompt = f"{TRIGGER_WORD}, {prompt}".strip(", ")

            # ── D1: CAN EXISTING CACHE BE REUSED? ───────────────────────────
            entry = dict(file_fingerprint(img_path))
            entry["caption_sha1"] = caption_fingerprint(prompt)

            def is_cached(out_dir):
                previous = manifests[out_dir].get("entries", {}).get(stem)
                if previous is None:
                    return False
                if {k: previous.get(k) for k in entry} != entry:
                    return False
                names = [stem] + ([f"{stem}__flip"] if FLIP_X else [])
                return all(os.path.exists(os.path.join(out_dir, f"{n}{suffix}"))
                           for n in names for suffix in ("_latent.pt", "_embed.pt", "_mask.pt"))

            pending = [(out_dir, area) for out_dir, area in targets if not is_cached(out_dir)]
            if not pending:
                reused += 1
                print(f"[{idx}/{len(image_files)}] Up to date: {file_name}")
                for out_dir, _ in targets:
                    manifests[out_dir].setdefault("entries", {})[stem] = entry
                continue

            print(f"[{idx}/{len(image_files)}] Processing: {file_name}")
            try:
                img = Image.open(img_path).convert("RGB")
            except Exception as err:
                print(f"[!] Warning: Cannot open image '{file_name}': {err}")
                continue

            # ── 1. TEXT → EMBEDDINGS (resolution-independent) ───────────────
            embeds, mask = pipe.encode_prompt(prompt=prompt, max_sequence_length=MAX_SEQ_LEN)
            embeds_cpu, mask_cpu = embeds.cpu(), mask.cpu()
            del embeds, mask

            # ── 2. IMAGE → LATENTS (VAE), once per resolution ───────────────
            # D2: horizontal flip is cached as another entry (`stem__flip`). The
            # trainer picks it up in its directory scan without any modification,
            # and the epoch sampler ensures both original and mirror are seen.
            variants = [("", img)]
            if FLIP_X:
                variants.append(("__flip", img.transpose(Image.FLIP_LEFT_RIGHT)))

            sizes = []
            for out_dir, area in pending:
                for suffix, variant in variants:
                    bw, bh, latent = vae_latent(variant, area)
                    name = f"{stem}{suffix}"
                    torch.save(latent,     os.path.join(out_dir, f"{name}_latent.pt"))
                    torch.save(embeds_cpu, os.path.join(out_dir, f"{name}_embed.pt"))
                    torch.save(mask_cpu,   os.path.join(out_dir, f"{name}_mask.pt"))
                    free_vram(latent)
                sizes.append(f"{bw}x{bh}")

            for out_dir, _ in targets:
                manifests[out_dir].setdefault("entries", {})[stem] = entry
            encoded += 1
            flip_note = " (+flip)" if FLIP_X else ""
            print(f"   [OK] {' · '.join(sizes)}{flip_note} | Latents & Embeddings cached.")

    # The manifest is reconstructed based on images actually present:
    # keeping stale entries would cause a deleted or renamed image to still
    # be considered valid, and its latent would never be reported as orphaned.
    present_names = {os.path.splitext(f)[0] for f in image_files}
    for out_dir, _ in targets:
        entries = {name: data
                   for name, data in manifests[out_dir].get("entries", {}).items()
                   if name in present_names}
        save_manifest(out_dir, entries)
        valid = list(entries) + ([f"{n}__flip" for n in entries] if FLIP_X else [])
        prune_orphans(out_dir, valid)

    free_vram(pipe)
    print(f"\n✓ Pre-caching finished! {encoded} encoded, {reused} reused, VRAM freed.")


if __name__ == "__main__":
    preprocess_krea2()