# -*- coding: utf-8 -*-
"""
run_progressive.py — Progressive-resolution training orchestrator.
Progressive-resolution training orchestrator for Krea 2.

Executes LoRA training in phases (e.g., 512² → 768² → 1024²) as
independent, sequential PyTorch subprocesses. Each phase starts with a
clean process (fresh CUDA allocator, no accumulated fragmentation), initializes
the LoRA with weights from the previous phase (init_lora_from), and resets the
optimizer. The resolution of each phase comes from the subdirectories generated by
1_pre_cache_krea2.py.

Reads train_settings.json without modifying it: writes a settings file per
phase and passes it to the trainer via the TRAIN_SETTINGS_PATH env-var.
"""
import os
import sys
import json
import time
import signal
import shutil
import subprocess
from pathlib import Path

try:
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")
except Exception:
    pass

# BASE_DIR is scripts/python/; PROJECT_ROOT is the project root, against
# which configuration and generated data are resolved.
BASE_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = BASE_DIR.parent.parent

TRAIN_SCRIPT = BASE_DIR / "2_train_lora_krea2.py"
CONFIG_PATH = os.environ.get("TRAIN_SETTINGS_PATH", str(PROJECT_ROOT / "train_settings.json"))
PHASE_SETTINGS_DIR = PROJECT_ROOT / ".progressive_phases"

# Container directories: everything generated is grouped here instead of the root.
CACHE_ROOT = str(PROJECT_ROOT / "cached_data_local")
OUTPUT_ROOT = str(PROJECT_ROOT / "output_local")

# ── PHASE PRESETS ────────────────────────────────────────────────────────────
# label: cache subdir (generated by pre-cache with round(sqrt(area))).
# portion: fraction of total_steps dedicated to the phase.
# gc: gradient_checkpointing (True = safe/slow, False = fast/more VRAM).
# Checkpointing flags per phase are conservative by default (True);
# they can be tuned after measuring actual VRAM at each resolution.
PRESETS = {
    # ── Constant resolution (single phase, all steps) ────────────────────────
    # Same pipeline as progressive, but without hand-off between phases. Useful
    # for experimenting at a fixed resolution by reusing subdirs from cache:
    # if you already pre-cached in progressive mode, subdirs 512/, 768/, and 1024/
    # already exist and you can run any of these without pre-caching again.
    # Output goes to phase0_<label>/, so 512, 768, and 1024 do not overwrite each
    # other and can be compared within the same project.
    "512":  [{"label": "512",  "portion": 1.0, "gc": True}],
    "768":  [{"label": "768",  "portion": 1.0, "gc": True}],
    "1024": [{"label": "1024", "portion": 1.0, "gc": True}],

    # ── Progressive (multi-phase with weight hand-off) ───────────────────────
    "768_1024": [
        {"label": "768",  "portion": 0.70, "gc": True},
        {"label": "1024", "portion": 0.30, "gc": True},
    ],
    "512_768_1024": [
        {"label": "512",  "portion": 0.40, "gc": True},
        {"label": "768",  "portion": 0.30, "gc": True},
        {"label": "1024", "portion": 0.30, "gc": True},
    ],
}

_current_child = None
_stop_requested = False


def _forward_signal(signum, frame):
    """Forwards stop signal to child trainer so it saves a checkpoint."""
    global _stop_requested
    _stop_requested = True
    child = _current_child
    if child is not None and child.poll() is None:
        try:
            child.send_signal(signal.SIGINT)
        except Exception:
            try:
                child.terminate()
            except Exception:
                pass


def _phase_done(phase_output, step_count):
    """True if the phase already reached its step count (complete checkpoint)."""
    try:
        with open(os.path.join(phase_output, "current_step.txt"), "r", encoding="utf-8") as f:
            return int(f.read().strip()) >= step_count
    except Exception:
        return False


def _run_signature(cfg, preset, total_steps, cache_base):
    """Configuration identity: if changed, previous weights are no longer valid."""
    return "|".join(str(x) for x in (
        preset, total_steps, cache_base,
        cfg.get("lora_rank"), cfg.get("lora_alpha"), cfg.get("lora_target"),
    ))


def resolve_run_id(output_base, signature, phase_outputs, step_counts):
    """Decides if this is a new run or the resumption of an interrupted one.

    The trainer prioritizes its own checkpoint over init_lora_from, so
    without this marker a re-launched pipeline would restore old weights from each phase,
    ignore the hand-off, and run an empty loop reporting success. The run_id
    allows each phase to distinguish 'my checkpoint' from 'that of a previous run'.
    """
    state_path = os.path.join(output_base, ".progressive_run.json")
    state = {}
    try:
        with open(state_path, "r", encoding="utf-8") as f:
            state = json.load(f)
    except Exception:
        state = {}

    pipeline_done = all(_phase_done(o, sc) for o, sc in zip(phase_outputs, step_counts))
    resuming = bool(state.get("run_id")) and state.get("signature") == signature and not pipeline_done

    # The random suffix prevents two runs within the same second from sharing an ID:
    # with a repeated ID, checkpoints from the previous run would be considered valid again.
    run_id = state["run_id"] if resuming else f"{time.strftime('%Y%m%d-%H%M%S')}-{os.urandom(3).hex()}"
    os.makedirs(output_base, exist_ok=True)
    try:
        with open(state_path, "w", encoding="utf-8") as f:
            json.dump({"run_id": run_id, "signature": signature}, f, indent=2)
    except Exception as exc:
        print(f"[!] Could not write run state: {exc}")
    return run_id, resuming


def derive_dirs(cfg):
    """Reproduces project_name → directories logic from scripts."""
    def anchor(path):
        """Relative paths in JSON are resolved against the project root."""
        return path if os.path.isabs(path) else os.path.normpath(os.path.join(str(PROJECT_ROOT), path))

    project = str(cfg.get("project_name", "")).strip()
    if project:
        cache_base = os.path.join(CACHE_ROOT, project)
        output_base = os.path.join(OUTPUT_ROOT, project)
    else:
        cache_base = anchor(cfg.get("cache_dir", os.path.join(CACHE_ROOT, "default")))
        output_base = anchor(cfg.get("output_dir", os.path.join(OUTPUT_ROOT, "default")))
    return cache_base, output_base


def main():
    signal.signal(signal.SIGINT, _forward_signal)
    signal.signal(signal.SIGTERM, _forward_signal)

    if not os.path.exists(CONFIG_PATH):
        print(f"[!] {CONFIG_PATH} not found.")
        return 1

    with open(CONFIG_PATH, "r", encoding="utf-8") as f:
        cfg = json.load(f)

    # Advanced sidecar: frozen inside phase JSONs so each
    # .progressive_phases/*.json remains self-describing and reproducible even if
    # train_advanced.json changes mid-run. train_settings.json takes precedence.
    advanced_path = os.environ.get("TRAIN_ADVANCED_PATH",
                                   os.path.join(str(PROJECT_ROOT), "train_advanced.json"))
    if os.path.exists(advanced_path):
        try:
            with open(advanced_path, "r", encoding="utf-8") as f:
                adv = json.load(f)
            cfg = {**adv, **cfg}
            print(f"[OK] Advanced settings merged from {advanced_path} ({len(adv)} keys)")
        except Exception as exc:
            print(f"[!] Could not read {advanced_path}: {exc} — ignoring.")

    preset = str(cfg.get("progressive", "off")).strip().lower()
    if preset in ("off", "", "none"):
        print("[!] 'progressive' is off; nothing to orchestrate. Run the trainer directly.")
        return 1
    if preset in PRESETS:
        phases = [dict(p) for p in PRESETS[preset]]
    elif preset.isdigit():
        # Any constant resolution, not just the three with their own preset:
        # the label is the subdir name generated by pre-cache, which is
        # round(sqrt(area)). Thus "640" or "896" work without editing this file.
        phases = [{"label": preset, "portion": 1.0, "gc": True}]
        print(f"[i] Constant-resolution run at {preset}².")
    else:
        print(f"[!] Unknown resolution mode '{preset}'. Options: {list(PRESETS)} "
              f"or a bare resolution like \"640\".")
        return 1
    portions = cfg.get("phase_portions")
    if isinstance(portions, list) and len(portions) == len(phases):
        for p, val in zip(phases, portions):
            p["portion"] = float(val)

    cache_base, output_base = derive_dirs(cfg)
    total_steps = int(cfg.get("total_steps", 1200))

    # Step distribution per phase (guaranteeing ≥1 and summing to total_steps).
    step_counts = [max(1, round(p["portion"] * total_steps)) for p in phases]
    step_counts[-1] += total_steps - sum(step_counts)

    phase_outputs = [os.path.join(output_base, f"phase{i}_{p['label']}")
                     for i, p in enumerate(phases)]
    signature = _run_signature(cfg, preset, total_steps, cache_base)
    run_id, resuming = resolve_run_id(output_base, signature, phase_outputs, step_counts)

    PHASE_SETTINGS_DIR.mkdir(exist_ok=True)
    print("=" * 70)
    if len(phases) == 1:
        print(f"CONSTANT-RESOLUTION TRAINING: {phases[0]['label']}²")
    else:
        print(f"PROGRESSIVE TRAINING: {preset}")
    print(f"  Cache base   : {cache_base}")
    print(f"  Output base  : {output_base}")
    print(f"  Total steps  : {total_steps}")
    print(f"  Run ID       : {run_id} ({'RESUMING' if resuming else 'NEW'})")
    if not resuming:
        print("  Previous-run checkpoints are discarded.")
    for i, (p, sc) in enumerate(zip(phases, step_counts)):
        prefix = "  Resolution" if len(phases) == 1 else f"  Phase {i}:"
        print(f"{prefix} {p['label']}²  {sc} steps  gc={'ON' if p['gc'] else 'OFF'}")
    print("=" * 70, flush=True)

    prev_resume = None
    t0_all = time.time()

    for i, (phase, sc) in enumerate(zip(phases, step_counts)):
        if _stop_requested:
            print("\n[!] Stop requested; aborting remaining phases.")
            break

        label = phase["label"]
        phase_cache = os.path.join(cache_base, label)
        if not os.path.isdir(phase_cache):
            print(f"\n[!] Cache subdir not found: {phase_cache}")
            print(f"[!] Run the Pre-Cache including {label}² in the "
                  f"'resolutions' list.")
            return 1

        phase_output = phase_outputs[i]

        # Phase settings: omit project_name so explicit cache/output override.
        phase_cfg = dict(cfg)
        phase_cfg.pop("project_name", None)
        phase_cfg.pop("progressive", None)
        phase_cfg.pop("phase_portions", None)
        phase_cfg.update({
            "cache_dir": phase_cache,
            "output_dir": phase_output,
            "total_steps": int(sc),
            "gradient_checkpointing": bool(phase["gc"]),
            "init_lora_from": prev_resume or "",
            "run_id": run_id,
            # Only for progress line: without this console resets step,
            # LR, and loss per phase, making training appear to restart from scratch.
            "phase_index": i,
            "phase_count": len(phases),
            "phase_label": label,
            "global_step_offset": int(sum(step_counts[:i])),
            "global_total_steps": int(total_steps),
        })
        if "batch" in phase:
            phase_cfg["batch_size"] = int(phase["batch"])

        phase_settings_path = PHASE_SETTINGS_DIR / f"phase{i}_{label}.json"
        with open(phase_settings_path, "w", encoding="utf-8") as f:
            json.dump(phase_cfg, f, indent=2, ensure_ascii=False)

        print(f"\n{'#' * 70}")
        if len(phases) == 1:
            print(f"# {label}²  ({sc} steps)")
        else:
            print(f"# PHASE {i+1}/{len(phases)} — {label}²  ({sc} steps)")
        print(f"{'#' * 70}", flush=True)

        env = dict(os.environ)
        env["TRAIN_SETTINGS_PATH"] = str(phase_settings_path)

        global _current_child
        _current_child = subprocess.Popen(
            [sys.executable, "-u", str(TRAIN_SCRIPT)],
            cwd=str(PROJECT_ROOT),
            env=env,
            stdin=subprocess.DEVNULL,
        )
        ret = _current_child.wait()
        _current_child = None

        if ret != 0:
            print(f"\n[!] Phase {i} exited with code {ret}.")
            if _stop_requested:
                break
            print("[!] Aborting pipeline.")
            return ret

        prev_resume = os.path.join(phase_output, "resume_checkpoint")
        if not os.path.exists(os.path.join(prev_resume, "adapter_model.safetensors")):
            print(f"\n[!] No hand-off checkpoint after phase {i}: {prev_resume}")
            print("[!] Cannot continue without phase weights.")
            return 1

    # Export the LoRA from the last completed phase to the final target filename.
    if prev_resume and not _stop_requested:
        last_output = os.path.dirname(prev_resume)
        last_lora = os.path.join(last_output, "Krea2_FINAL_LoRA.safetensors")
        default_name = (f"Krea2_{phases[0]['label']}_FINAL.safetensors" if len(phases) == 1
                        else "Krea2_Progressive_FINAL.safetensors")
        final_name = str(cfg.get("export_final_name", "")).strip() or default_name
        dest_dir = str(cfg.get("export_models_dir", "")).strip() or output_base
        os.makedirs(dest_dir, exist_ok=True)
        dest = os.path.join(dest_dir, final_name)
        if os.path.exists(last_lora):
            try:
                shutil.copy2(last_lora, dest)
                print(f"\n✓ Final LoRA: {dest}")
            except Exception as exc:
                print(f"[!] Could not copy final LoRA: {exc}")

    dt = time.time() - t0_all
    kind = "Run" if len(phases) == 1 else "Progressive pipeline"
    print(f"\n✓ {kind} finished in "
          f"{int(dt//3600):02d}:{int((dt%3600)//60):02d}:{int(dt%60):02d}")
    return 0


if __name__ == "__main__":
    sys.exit(main())